name: Build Bloomcoin Wallets

on:
  push:
    branches:
      - master
  release:
    types: [published]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    name: Linux Wallet
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libtool autotools-dev automake pkg-config \
            libssl-dev libevent-dev bsdmainutils libboost-all-dev libdb-dev libdb++-dev \
            libminiupnpc-dev libzmq3-dev libprotobuf-dev protobuf-compiler libqrencode-dev qttools5-dev qttools5-dev-tools qtbase5-dev
      - name: Build
        run: |
          ./autogen.sh
          ./configure --with-incompatible-bdb
          make -j$(nproc)
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: bloomcoin-linux-wallet
          path: |
            src/bloomcoind
            src/qt/bloomcoin-qt

  build-windows:
    runs-on: windows-latest
    name: Windows Wallet
    steps:
      - uses: actions/checkout@v3
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          install: >-
            base-devel
            mingw-w64-x86_64-toolchain
            git
            mingw-w64-x86_64-boost
            mingw-w64-x86_64-qt5
            mingw-w64-x86_64-cmake
      - name: Build
        shell: msys2 {0}
        run: |
          ./autogen.sh
          ./configure --host=x86_64-w64-mingw32
          make -j4
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: bloomcoin-windows-wallet
          path: |
            src/*.exe
            qt/*.exe

  build-macos:
    runs-on: macos-latest
    name: macOS Wallet
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          brew install automake berkeley-db boost libevent qt protobuf
      - name: Build
        run: |
          ./autogen.sh
          ./configure
          make -j$(sysctl -n hw.ncpu)
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: bloomcoin-macos-wallet
          path: |
            src/bloomcoind
            src/qt/bloomcoin-qt

  release-artifacts:
    needs: [build-linux, build-windows, build-macos]
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts
      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/**/*

